[package]
name = "Pyru"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.8"
thiserror = "2.0.12"
