[package]
name = "interpreter_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.5"
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0.198", features = ["derive"] }
sha2 = "0.10.8"
thiserror = "1.0.58"
